package com.guty.siemlite.repository;

import com.guty.siemlite.model.Incident;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

/**
 * Repository responsible for interacting with the Incident table.
 *
 * <p>Provides persistence operations for correlated security incidents
 * generated by the correlation engine.</p>
 */
public interface IncidentRepository extends JpaRepository<Incident, Long> {

    /**
     * Determines whether an incident already exists for a source IP and type.
     *
     * @param sourceIp source IP address
     * @param incidentType incident type
     * @return true if a matching incident already exists
     */
    boolean existsBySourceIpAndIncidentType(String sourceIp, String incidentType);

    /**
     * Finds incidents for a specific source IP address.
     *
     * @param sourceIp source IP address
     * @return matching incidents
     */
    List<Incident> findBySourceIp(String sourceIp);
}
