package com.guty.siemlite.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/*
 * Represents a security alert generated by the DetectionService.
 *
 * Alerts are higher-level findings produced from one or more events.
 *
 * Examples:
 *
 * BRUTE_FORCE_ATTEMPT
 * ACCOUNT_COMPROMISE
 *
 * Alerts are stored in the database and retrieved
 * through GET /api/alerts.
 */
@Entity
public class Alert {

    /*
     * Primary key.
     *
     * Generated automatically by H2.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /*
     * Time when the alert was generated.
     */
    private LocalDateTime timestamp;

    /*
     * Type of alert.
     *
     * Examples:
     *
     * BRUTE_FORCE_ATTEMPT
     * ACCOUNT_COMPROMISE
     */
    private String alertType;

    /*
     * Severity level.
     *
     * Examples:
     *
     * LOW
     * MEDIUM
     * HIGH
     * CRITICAL
     */
    private String severity;

    /*
     * Human-readable explanation of the alert.
     *
     * Example:
     *
     * "Possible brute force attack detected from 192.168.1.60"
     */
    private String message;

    /*
     * Source IP associated with the alert.
     */
    private String sourceIp;

    /*
     * Default constructor required by JPA.
     */
    public Alert() {
    }

    /*
     * Constructor used when creating alerts.
     */
    public Alert(LocalDateTime timestamp,
                 String alertType,
                 String severity,
                 String message,
                 String sourceIp) {

        this.timestamp = timestamp;
        this.alertType = alertType;
        this.severity = severity;
        this.message = message;
        this.sourceIp = sourceIp;
    }

    // ===== GETTERS =====

    /*
     * Returns alert ID.
     */
    public Long getId() {
        return id;
    }

    /*
     * Returns alert timestamp.
     */
    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    /*
     * Returns alert type.
     */
    public String getAlertType() {
        return alertType;
    }

    /*
     * Returns severity.
     */
    public String getSeverity() {
        return severity;
    }

    /*
     * Returns alert message.
     */
    public String getMessage() {
        return message;
    }

    /*
     * Returns source IP.
     */
    public String getSourceIp() {
        return sourceIp;
    }

    // ===== SETTERS =====

    /*
     * Sets alert ID.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /*
     * Sets timestamp.
     */
    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    /*
     * Sets alert type.
     */
    public void setAlertType(String alertType) {
        this.alertType = alertType;
    }

    /*
     * Sets severity.
     */
    public void setSeverity(String severity) {
        this.severity = severity;
    }

    /*
     * Sets alert message.
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /*
     * Sets source IP.
     */
    public void setSourceIp(String sourceIp) {
        this.sourceIp = sourceIp;
    }
}