package com.guty.siemlite.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/*
 * Represents a security alert generated by the DetectionService.
 */
@Entity
public class Alert {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private LocalDateTime timestamp;

    private String alertType;

    private String severity;

    private Integer riskScore;

    private String message;

    private String sourceIp;

    private String mitreTechnique;

    private String mitreDescription;

    private String status;

    private String assignedAnalyst;

    @Column(length = 2000)
    private String notes;

    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;

    public Alert() {
    }

    public Alert(LocalDateTime timestamp,
                 String alertType,
                 String severity,
                 Integer riskScore,
                 String message,
                 String sourceIp) {

        this.timestamp = timestamp;
        this.alertType = alertType;
        this.severity = severity;
        this.riskScore = riskScore;
        this.message = message;
        this.sourceIp = sourceIp;

        this.status = "OPEN";
        this.assignedAnalyst = null;
        this.notes = null;
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    public Long getId() {
        return id;
    }

    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    public String getAlertType() {
        return alertType;
    }

    public String getSeverity() {
        return severity;
    }

    public Integer getRiskScore() {
        return riskScore;
    }

    public String getMessage() {
        return message;
    }

    public String getSourceIp() {
        return sourceIp;
    }

    public String getMitreTechnique() {
        return mitreTechnique;
    }

    public String getMitreDescription() {
        return mitreDescription;
    }

    public String getStatus() {
        return status;
    }

    public String getAssignedAnalyst() {
        return assignedAnalyst;
    }

    public String getNotes() {
        return notes;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    public void setAlertType(String alertType) {
        this.alertType = alertType;
    }

    public void setSeverity(String severity) {
        this.severity = severity;
    }

    public void setRiskScore(Integer riskScore) {
        this.riskScore = riskScore;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public void setSourceIp(String sourceIp) {
        this.sourceIp = sourceIp;
    }

    public void setMitreTechnique(String mitreTechnique) {
        this.mitreTechnique = mitreTechnique;
    }

    public void setMitreDescription(String mitreDescription) {
        this.mitreDescription = mitreDescription;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public void setAssignedAnalyst(String assignedAnalyst) {
        this.assignedAnalyst = assignedAnalyst;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}