package com.guty.siemlite.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/*
 * Represents a security alert generated by the DetectionService.
 *
 * Alerts are higher-level findings produced from one or more events.
 *
 * Examples:
 *
 * BRUTE_FORCE_ATTEMPT
 * ACCOUNT_COMPROMISE
 * PRIVILEGE_ESCALATION
 *
 * Alerts are stored in the database and retrieved
 * through GET /api/alerts.
 */
@Entity
public class Alert {

    /*
     * Primary key.
     *
     * Generated automatically by H2.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /*
     * Time when the alert was generated.
     */
    private LocalDateTime timestamp;

    /*
     * Type of alert.
     *
     * Examples:
     *
     * BRUTE_FORCE_ATTEMPT
     * ACCOUNT_COMPROMISE
     * PRIVILEGE_ESCALATION
     */
    private String alertType;

    /*
     * Severity level.
     *
     * Examples:
     *
     * LOW
     * MEDIUM
     * HIGH
     * CRITICAL
     */
    private String severity;

    /*
     * Human-readable explanation of the alert.
     */
    private String message;

    /*
     * Source IP associated with the alert.
     */
    private String sourceIp;

    /*
     * Alert lifecycle status.
     *
     * OPEN
     * INVESTIGATING
     * CLOSED
     */
    private String status;

    /*
     * Analyst assigned to investigate the alert.
     */
    private String assignedAnalyst;

    /*
     * Investigation notes.
     */
    @Column(length = 2000)
    private String notes;

    /*
     * Time when the alert record was created.
     */
    private LocalDateTime createdAt;

    /*
     * Time when the alert record was last updated.
     */
    private LocalDateTime updatedAt;

    /*
     * Default constructor required by JPA.
     */
    public Alert() {
    }

    /*
     * Constructor used when creating alerts.
     */
    public Alert(LocalDateTime timestamp,
                 String alertType,
                 String severity,
                 String message,
                 String sourceIp) {

        this.timestamp = timestamp;
        this.alertType = alertType;
        this.severity = severity;
        this.message = message;
        this.sourceIp = sourceIp;

        /*
         * Default alert lifecycle values.
         */
        this.status = "OPEN";
        this.assignedAnalyst = null;
        this.notes = null;
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    // ===== GETTERS =====

    public Long getId() {
        return id;
    }

    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    public String getAlertType() {
        return alertType;
    }

    public String getSeverity() {
        return severity;
    }

    public String getMessage() {
        return message;
    }

    public String getSourceIp() {
        return sourceIp;
    }

    public String getStatus() {
        return status;
    }

    public String getAssignedAnalyst() {
        return assignedAnalyst;
    }

    public String getNotes() {
        return notes;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    // ===== SETTERS =====

    public void setId(Long id) {
        this.id = id;
    }

    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    public void setAlertType(String alertType) {
        this.alertType = alertType;
    }

    public void setSeverity(String severity) {
        this.severity = severity;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public void setSourceIp(String sourceIp) {
        this.sourceIp = sourceIp;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public void setAssignedAnalyst(String assignedAnalyst) {
        this.assignedAnalyst = assignedAnalyst;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}