package com.guty.siemlite.controller;

import com.guty.siemlite.model.Incident;
import com.guty.siemlite.service.IncidentService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * REST controller for managing security incidents.
 *
 * <p>Provides endpoints for retrieving and managing correlated incidents
 * generated by the SIEM correlation engine.</p>
 */
@RestController
@RequestMapping("/api/incidents")
public class IncidentController {

    private final IncidentService incidentService;

    public IncidentController(IncidentService incidentService) {
        this.incidentService = incidentService;
    }

    /**
     * Returns all incidents.
     *
     * @return list of incidents
     */
    @GetMapping
    public List<Incident> getAllIncidents() {
        return incidentService.getAllIncidents();
    }

    /**
     * Returns a single incident by its ID.
     *
     * @param id incident identifier
     * @return incident if found, otherwise 404
     */
    @GetMapping("/{id}")
    public ResponseEntity<Incident> getIncidentById(@PathVariable Long id) {
        try {
            return ResponseEntity.ok(incidentService.getIncidentById(id));
        } catch (IllegalArgumentException e) {
            return ResponseEntity.notFound().build();
        }
    }

    /**
     * Assigns an incident to an analyst.
     *
     * @param id incident identifier
     * @param assignedAnalyst analyst assigned to the incident
     * @return updated incident if found, otherwise 404
     */
    @PutMapping("/{id}/assign")
    public ResponseEntity<Incident> assignIncident(
            @PathVariable Long id,
            @RequestParam String assignedAnalyst) {
        try {
            return ResponseEntity.ok(incidentService.assignIncident(id, assignedAnalyst));
        } catch (IllegalArgumentException e) {
            return ResponseEntity.notFound().build();
        }
    }

    /**
     * Updates the status of an incident.
     *
     * @param id incident identifier
     * @param status new incident status
     * @return updated incident if found, otherwise 404
     */
    @PutMapping("/{id}/status")
    public ResponseEntity<Incident> updateIncidentStatus(
            @PathVariable Long id,
            @RequestParam String status) {
        try {
            return ResponseEntity.ok(incidentService.updateIncidentStatus(id, status));
        } catch (IllegalArgumentException e) {
            return ResponseEntity.notFound().build();
        }
    }

    /**
     * Updates the notes of an incident.
     *
     * @param id incident identifier
     * @param notes incident notes
     * @return updated incident if found, otherwise 404
     */
    @PutMapping("/{id}/notes")
    public ResponseEntity<Incident> updateIncidentNotes(
            @PathVariable Long id,
            @RequestParam String notes) {
        try {
            return ResponseEntity.ok(incidentService.updateIncidentNotes(id, notes));
        } catch (IllegalArgumentException e) {
            return ResponseEntity.notFound().build();
        }
    }
}
