import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
    Box,
    Button,
    Chip,
    CircularProgress,
    Dialog,
    DialogActions,
    DialogContent,
    DialogTitle,
    Paper,
    Table,
    TableBody,
    TableCell,
    TableContainer,
    TableHead,
    TableRow,
    TextField,
    Typography,
} from "@mui/material";

import {
    assignAlert,
    getAlerts,
    getRelatedEvents,
    updateAlertNotes,
    updateAlertStatus,
} from "../services/alerts";

import AlertDetailsDrawer from "../components/AlertDetailsDrawer";
import type { Alert } from "../types/alert";
import type { SecurityEvent } from "../types/event";

function getSeverityColor(
    severity: string
): "default" | "error" | "warning" | "info" | "success" {
    switch (severity?.toUpperCase()) {
        case "CRITICAL":
            return "error";
        case "HIGH":
            return "warning";
        case "MEDIUM":
            return "info";
        case "LOW":
            return "success";
        default:
            return "default";
    }
}

export default function AlertsPage() {
    const navigate = useNavigate();

    const [alerts, setAlerts] = useState<Alert[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");

    const [selectedAlert, setSelectedAlert] = useState<Alert | null>(null);
    const [relatedEvents, setRelatedEvents] = useState<SecurityEvent[]>([]);
    const [drawerOpen, setDrawerOpen] = useState(false);
    const [assignOpen, setAssignOpen] = useState(false);

    const [analyst, setAnalyst] = useState("");
    const [notes, setNotes] = useState("");

    async function loadAlerts() {
        try {
            const data = await getAlerts();
            setAlerts(data);
            setError("");
        } catch {
            setError("Failed to load alerts.");
        } finally {
            setLoading(false);
        }
    }

    useEffect(() => {
        loadAlerts();
    }, []);

    async function handleStatusChange(id: number, status: string) {
        await updateAlertStatus(id, status);

        setAlerts((currentAlerts) =>
            currentAlerts.map((alert) =>
                alert.id === id ? { ...alert, status } : alert
            )
        );

        if (selectedAlert?.id === id) {
            setSelectedAlert({ ...selectedAlert, status });
        }

        await loadAlerts();
    }

    async function openDrawer(alert: Alert) {
        setSelectedAlert(alert);
        setNotes(alert.notes ?? "");
        setRelatedEvents([]);
        setDrawerOpen(true);

        try {
            const events = await getRelatedEvents(alert.id);
            setRelatedEvents(events);
        } catch {
            setRelatedEvents([]);
        }
    }

    function closeDrawer() {
        setDrawerOpen(false);
        setRelatedEvents([]);
    }

    function openAssignDialog(alert: Alert) {
        setSelectedAlert(alert);
        setAnalyst(alert.assignedAnalyst ?? "");
        setAssignOpen(true);
    }

    async function handleAssignSave() {
        if (!selectedAlert) return;

        await assignAlert(selectedAlert.id, analyst);

        setSelectedAlert({
            ...selectedAlert,
            assignedAnalyst: analyst,
        });

        setAlerts((currentAlerts) =>
            currentAlerts.map((alert) =>
                alert.id === selectedAlert.id
                    ? { ...alert, assignedAnalyst: analyst }
                    : alert
            )
        );

        setAssignOpen(false);
        await loadAlerts();
    }

    async function handleNotesSave() {
        if (!selectedAlert) return;

        await updateAlertNotes(selectedAlert.id, notes);

        setSelectedAlert({
            ...selectedAlert,
            notes,
        });

        setAlerts((currentAlerts) =>
            currentAlerts.map((alert) =>
                alert.id === selectedAlert.id ? { ...alert, notes } : alert
            )
        );

        await loadAlerts();
    }

    function handlePivot(
        field: "sourceIp" | "username" | "mitreTechnique",
        value: string
    ) {
        navigate(`/events?${field}=${encodeURIComponent(value)}`);
    }

    if (loading) {
        return (
            <Box sx={{ display: "flex", justifyContent: "center", marginTop: 6 }}>
                <CircularProgress />
            </Box>
        );
    }

    return (
        <Box>
            <Typography
                variant="h4"
                component="h1"
                sx={{ fontWeight: 700, marginBottom: 1 }}
            >
                Alerts
            </Typography>

            <Typography
                variant="body1"
                component="p"
                color="text.secondary"
                sx={{ marginBottom: 3 }}
            >
                Security alerts generated by the SIEM-Lite detection engine.
            </Typography>

            {error !== "" && (
                <Typography component="p" color="error" sx={{ marginBottom: 2 }}>
                    {error}
                </Typography>
            )}

            <TableContainer component={Paper}>
                <Table>
                    <TableHead>
                        <TableRow>
                            <TableCell>Severity</TableCell>
                            <TableCell>Alert Type</TableCell>
                            <TableCell>Risk Score</TableCell>
                            <TableCell>MITRE Technique</TableCell>
                            <TableCell>Status</TableCell>
                            <TableCell>Assigned Analyst</TableCell>
                            <TableCell>Created</TableCell>
                            <TableCell>Actions</TableCell>
                        </TableRow>
                    </TableHead>

                    <TableBody>
                        {alerts.length === 0 ? (
                            <TableRow>
                                <TableCell colSpan={8}>No alerts found.</TableCell>
                            </TableRow>
                        ) : (
                            alerts.map((alert) => (
                                <TableRow key={alert.id} hover>
                                    <TableCell>
                                        <Chip
                                            label={alert.severity ?? "UNKNOWN"}
                                            color={getSeverityColor(alert.severity)}
                                            size="small"
                                        />
                                    </TableCell>

                                    <TableCell>{alert.alertType ?? alert.type ?? "N/A"}</TableCell>
                                    <TableCell>{alert.riskScore ?? 0}</TableCell>
                                    <TableCell>{alert.mitreTechnique ?? "N/A"}</TableCell>
                                    <TableCell>{alert.status ?? "OPEN"}</TableCell>
                                    <TableCell>{alert.assignedAnalyst ?? "Unassigned"}</TableCell>

                                    <TableCell>
                                        {alert.createdAt
                                            ? new Date(alert.createdAt).toLocaleString()
                                            : "N/A"}
                                    </TableCell>

                                    <TableCell>
                                        <Button
                                            size="small"
                                            variant="contained"
                                            onClick={() => openDrawer(alert)}
                                        >
                                            View
                                        </Button>
                                    </TableCell>
                                </TableRow>
                            ))
                        )}
                    </TableBody>
                </Table>
            </TableContainer>

            <AlertDetailsDrawer
                open={drawerOpen}
                alert={selectedAlert}
                relatedEvents={relatedEvents}
                notes={notes}
                onNotesChange={setNotes}
                onClose={closeDrawer}
                onStatusChange={handleStatusChange}
                onSaveNotes={handleNotesSave}
                onOpenAssign={openAssignDialog}
                onPivot={handlePivot}
            />

            <Dialog open={assignOpen} onClose={() => setAssignOpen(false)} fullWidth>
                <DialogTitle>Assign Alert</DialogTitle>
                <DialogContent>
                    <TextField
                        label="Analyst"
                        fullWidth
                        value={analyst}
                        onChange={(event) => setAnalyst(event.target.value)}
                        sx={{ marginTop: 2 }}
                    />
                </DialogContent>
                <DialogActions>
                    <Button onClick={() => setAssignOpen(false)}>Cancel</Button>
                    <Button variant="contained" onClick={handleAssignSave}>
                        Save
                    </Button>
                </DialogActions>
            </Dialog>
        </Box>
    );
}